# Generated by Django 4.2.2 on 2023-06-23 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Department Code')),
                ('name', models.CharField(max_length=100, verbose_name='Department Name')),
                ('description', models.TextField(verbose_name='Department Description')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Unit Code')),
                ('name', models.CharField(max_length=100, verbose_name='Unit Name')),
                ('description', models.TextField(verbose_name='Unit Description')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.department')),
            ],
        ),
    ]
